config/routes.rb
Toomanychips::Application.routes.draw do

  match 'auth/:provider/callback', to: 'session#oauth_create'
  match 'auth/failure', to: redirect('/')

  root to: 'pages#index'
  resources :users, :only => [:show, :create, :new, :edit] 
  get '/your_profile', to: 'users#your_profile', as: 'your_profile'
  resources :session, :only => [:destroy, :create]
  post '/login' => 'session#create', :as => 'login'
  match 'signout', to: 'session#destroy', as: 'signout'

  resources :events
  get '/:url' => 'events#invitation', :as => 'invitation'

  resources :items
  
  resources :assigned_items, :except => [:index]
  match 'remove', to: 'assigned_items#destroy', as: 'remove'
  resources :guests, :only => [:show, :edit, :new, :create]
  get '/rsvp/:url' => 'guests#show', :as => 'rsvp'

  mount Sidekiq::Web, at: "/sidekiq"

end

app/models/guest.rb
class Guest < ActiveRecord::Base
  before_save :set_url
  has_many :assigned_items, :dependent => :destroy
  has_many :event_items, :through => :assigned_items
  attr_accessible :name, :email, :url, :guest_id, :assigned_items_attributes

  accepts_nested_attributes_for :assigned_items

  def contributions(id)
    self.assigned_items.select { |item| item if (item.event_item.event_id == id) }
  end

  def set_url
    self.url ||= SecureRandom.urlsafe_base64
  end

end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def new
    @guest = Guest.new
    @guest.assigned_items.build
    @assigned_item = AssignedItem.new
  end

  def create
    if @guest = Guest.find_by_email(params[:guest][:email])
      params["guest"]["assigned_items_attributes"].each do |e|
        @guest.assigned_items << AssignedItem.new(quantity_provided: e[1]["quantity_provided"], event_item_id: e[1]["event_item_id"])
      end
    else @guest = Guest.new(params[:guest])
    end
    if @guest.save
      session[:guest_id] = @guest.id
      @event = @guest.assigned_items.first.event_item.event
      render :json => event_path(@event).to_json
    else
      render :json => @guest.errors.full_messages.join(','), :status => :unprocessable_entity
    end
  end

  def rsvp
    p params[:url]
    @guest = Guest.find_by_url(params[:url])
    render :show
  end

  def show
    p params[:url]
    @guest = Guest.find_by_url(params[:url])
    render :show
  end
end

app/views/guests/show.html.erb
 <div class='container'>
  <div class='guest-show'>
    <h4>You're signed up to bring: <h4>
      <table class='table'>
        <% @guest.assigned_items.each do |item| %>
        <tr>
          <th>Item</th>
          <th>How Many</th>
          <th>Item Information</th>
          <th>Link to Event</th>
          <th>Delete Item</th>
        </tr>
        <tr>  
          <td><%= item.event_item.item.name %></td>
          <td><%= item.quantity_provided %></td>
          <td><%= item.event_item.description%></td>
            <td> <%= link_to "#{item.event_item.event.name}", event_path(item.event_item.event)%></td>
            <td> <%= button_to 'remove', assigned_items_path(item), :method => :delete, :remote => :true %></td>
        <% end %>
      </table>
  </div>
</div> 