config/routes.rb
Toomanychips::Application.routes.draw do

  match 'auth/:provider/callback', to: 'session#oauth_create'
  match 'auth/failure', to: redirect('/')

  root to: 'pages#index'
  resources :users, :only => [:show, :create, :new, :edit] 
  get '/your_profile', to: 'users#your_profile', as: 'your_profile'
  resources :session, :only => [:destroy, :create]
  post '/login' => 'session#create', :as => 'login'
  match 'signout', to: 'session#destroy', as: 'signout'

  resources :events
  get '/:url' => 'events#invitation', :as => 'invitation'

  resources :items
  
  resources :assigned_items, :except => [:index]
  match 'remove', to: 'assigned_items#destroy', as: 'remove'
  resources :guests, :only => [:show, :edit, :new, :create]
  get '/rsvp/:url' => 'guests#show', :as => 'rsvp'

  mount Sidekiq::Web, at: "/sidekiq"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password
  has_many :events, :class_name => 'Event', :foreign_key => 'user_id'
  has_secure_password
  validates :name, :length  => {:minimum => 2, :too_short  => "must have at least 2 letters"}
  validates :email, :uniqueness => {:case_sensitive => false, :message => "has already been taken"}, :format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,:message    => "must be a valid format" }
  validates :password, :length => {:minimum => 6, :too_short  => "must have at least 6 characters"}
  validates_confirmation_of :password

  after_save :registration_emails!

  def token_expired?
    self.oauth_expires_at > DateTime.now
  end

  def self.from_omniauth(auth)
  	where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user = User.find_or_create_by_email(auth.info.email)
        if user.oauth_token.nil?
          user
        else
      		user.provider = auth.provider
      		user.uid = auth.uid
      		user.email = auth.info.email
      		user.name = auth.info.name
      		user.oauth_token = auth.credentials.token
      		user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      		user.password = user.password ||= SecureRandom.hex(4)
      		user.save!
        end
  	end
  end

  def registration_emails!
    # schedule_result_email unless self.result_date == nil
    send_email
  end

  # def schedule_result_email
  #   EmailWorker.perform_at(self.result_date, self.user_id, self.id, 'result')
  # end

  def send_email
    EmailWorker.perform_async(self.id)
  end

#   App ID: 505556099515765
# App Secret: e69b8e34f1011bf7c5aac0be544faa42

end



# <% if flash[:errors] %>
#   <% flash[:errors].each do |k, v| %>
#   <p class="session_errors"><%= k %>: <%= v.join(", ") %></p>

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :logged_in?, :only => [:show, :edit, :update, :destroy]
  before_filter :load_and_authorize_user, :only => [:show, :edit, :update, :destroy]

  def your_profile
    @user = current_user
    @event = Event.new
    @event.event_items.build.item = Item.new
    render :show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:id] = @user.id
      # UserMailer.signup_confirmation(@user.id).deliver
      redirect_to your_profile_path, notice: "You've successfully signed up!"
    else
      flash[:errors] = @user.errors.messages
      redirect_to root_path
    end
  end

  def destroy
    @user.destroy
  end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_login_form.html.erb
<%= form_for :session, url: session_path, :html => {:class => 'form-horizontal'} do |f| %>

<div class="control-group">
  <label class="control-label" for="inputEmail">Email</label>
  <div class="controls">
    <%= f.text_field :email, :id => "inputEmail", :required => true, :placeholder => :email %>
  </div>
</div>

<div class="control-group">
  <label class="control-label" for="inputPassword">Password</label>
  <div class="controls">
    <%= f.password_field :password, :id => "inputPassword", :required => true, :placeholder => :password %>
  </div>
</div>

    <%= f.submit "Log In", class: "btn btn-large btn-primary"%>
<%end%>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'signup_form' %>


<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="hero-unit" id="event_new">
	<div class='container'>
	</div>
</div>

	<div class="cover">


<div class="event-form-container container">
	<div class="row gnup_forms">
		<% if current_user.events.any? %>
		<div class="span6">
		<% else %>
		<div class="span7">
	  <% end %>
			<div class="gnup_container">
				<div class="gnup_form">
					<div class="errors">
					<%flash.each do |name,msg| %>
						<div class="alert alert-success">	
							<%=msg%>
						</div>
						<%end%>
						</div>
					<h2> 
						Welcome, <%= current_user.name.titleize %>! 
					</h2>
					<h3> 
						Account Details:
					</h3>
					<h4>
						Name: <%= current_user.name.titleize %>
					</h4>
					<h4>
						Email: <%= current_user.email %>
					</h4><br>
				<!-- 	<div class='user_edit_button'>
						<%#= button_to 'Edit', edit_user_path(current_user), class: "btn btn-info" %>
					</div> -->
					<div class="event_button">
            <a href="#eventform" class="btn btn-success"> Create Event </a>
          </div>
				</div>				
				<div class="cover"></div>
			</div>
		</div>

		<% if current_user.events.any? %>
			<div class="span6">
		<% else %>
			<div class="">
	  <% end %>
			<div class="gnup_container">
				<div class="gnin_form">
					<% upcoming = current_user.events.where('date>?', Date.today) %>

					<% if upcoming.any? %>
					<h2> 
						Upcoming Events: 
					</h2>
					
					<% current_user.events.each do |event| %>
					<% if event.upcoming? %>
					<ul>                    
						<h5>
							<li>
								<%= link_to event.name.titleize, event_path(event) %>: <%= event.date %>
							</li>
						</h5>
					</ul>
					<% end %>
					<% end %>
					<% end %>
					<% past = current_user.events.where('date<?', Date.today) %>

					<% if past.any? %>
					<h2> 
						Past Events: 
					</h2>
					
					<% current_user.events.each do |event| %>
					<% if event.past? %>
					<ul>
						<h5>
							<li>
								<%= link_to event.name.titleize, event_path(event) %>: <%= event.date %>
							</li>
						</h5>
					</ul>
					<% end %>
					<% end %>
					<% end %>


					
				</div>
				<div class="cover"></div>
			</div>
		</div>
	</div>
	  <%= render 'events/create_event_form' %>
</div>