config/routes.rb
Toomanychips::Application.routes.draw do

  match 'auth/:provider/callback', to: 'session#oauth_create'
  match 'auth/failure', to: redirect('/')

  root to: 'pages#index'
  resources :users, :only => [:show, :create, :new, :edit] 
  get '/your_profile', to: 'users#your_profile', as: 'your_profile'
  resources :session, :only => [:destroy, :create]
  post '/login' => 'session#create', :as => 'login'
  match 'signout', to: 'session#destroy', as: 'signout'

  resources :events
  get '/:url' => 'events#invitation', :as => 'invitation'

  resources :items
  
  resources :assigned_items, :except => [:index]
  match 'remove', to: 'assigned_items#destroy', as: 'remove'
  resources :guests, :only => [:show, :edit, :new, :create]
  get '/rsvp/:url' => 'guests#show', :as => 'rsvp'

  mount Sidekiq::Web, at: "/sidekiq"

end

app/views/layouts/_create_user_form.erb
<div id="new_account_errors">
  <% if flash[:errors] %>
  <% flash[:errors].each do |k, v| %>
  <p class="session_errors"><%= k %>: <%= v.join(", ") %></p>
  <% end %>
  <% end %>
</div>

<% @user = User.new %>
<%= form_for @user do |f| %>

  <%= f.text_field :name, :id => "inputName", :required => true, placeholder: "Name" %><br>
 
  <%= f.email_field :email, :id => "inputEmail", :required => true, placeholder: "Email" %><br>

  <%= f.password_field :password, :id => "inputPassword", :required => true, placeholder: "Password" %><br>
  <%= f.submit "Sign up", :class => 'btn btn-success' %>
<% end %>

app/views/layouts/_header.html.erb
<header>
	<nav class="navbar">
		<div class= "navbar-inner">
				<% if current_user %> 
				<h1 id="brand" ><a href="/your_profile">TOO<strong>MANY</strong>CHIPS</a></h1>
					<%= button_to "Sign Out", signout_path, id: "sign_out", class: :"btn btn-warning" %></li>
					<%= button_to "Your Profile", your_profile_path, :method => :get, id: "profile", class: :"btn btn-warning" %></li>
				<% else %>
					<h1 id="brand" ><a href="/">TOO<strong>MANY</strong>CHIPS</a></h1>
				<%end%>
			</ul>
		</div>
	</nav>
</header>

app/views/layouts/_user_login_form.html.erb
<%= form_tag session_index_path, :class => "login"  do %>
<%= email_field_tag :email, nil, placeholder: "Email" %><br>
<%= password_field_tag :password, nil, placeholder: "Password" %><br><br>
<%= submit_tag "Log In", class: "btn btn-success" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PotluckyGopher</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

     <link href='http://fonts.googleapis.com/css?family=Sniglet:800' rel='stylesheet' type='text/css'>
  </head>
  <body>
  	<%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>